import { StyleSheet } from 'react-native';
import { Theme } from '../../theme/theme';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    padding: Theme.spacing.md,
  },
  modalCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.borderRadius.lg,
    padding: Theme.spacing.lg,
    maxHeight: '85%',
    ...Theme.shadows.medium,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Theme.colors.primary,
    marginBottom: Theme.spacing.xs,
  },
  modalSubtitle: {
    fontSize: 14,
    color: Theme.colors.textMuted,
    marginBottom: Theme.spacing.md,
  },
  listContent: {
    paddingBottom: Theme.spacing.sm,
    gap: Theme.spacing.sm,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: Theme.spacing.md,
    borderRadius: Theme.borderRadius.md,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  rowIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Theme.colors.primary + '14',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Theme.spacing.md,
    marginTop: 2,
  },
  rowBody: {
    flex: 1,
    minWidth: 0,
  },
  rowKind: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: Theme.colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  rowItemName: {
    fontSize: 16,
    fontWeight: '700',
    color: Theme.colors.primary,
    lineHeight: 22,
  },
  rowMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginTop: Theme.spacing.sm,
  },
  qtyBadge: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: Theme.colors.secondary + '24',
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 6,
    borderRadius: Theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: Theme.colors.secondary + '55',
  },
  qtyNumber: {
    fontSize: 18,
    fontWeight: '800',
    color: Theme.colors.primary,
    fontVariant: ['tabular-nums'],
  },
  qtyUnitLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: Theme.colors.slate,
    marginLeft: 4,
  },
  categoryPill: {
    backgroundColor: Theme.colors.card,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 6,
    borderRadius: Theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: '#DEE2E6',
  },
  categoryPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: Theme.colors.text,
  },
  rowMessage: {
    fontSize: 15,
    color: Theme.colors.text,
    lineHeight: 21,
  },
  rowDate: {
    fontSize: 12,
    color: Theme.colors.textMuted,
    marginTop: Theme.spacing.sm,
  },
  emptyText: {
    fontSize: 15,
    color: Theme.colors.textMuted,
    textAlign: 'center',
    paddingVertical: Theme.spacing.lg,
  },
  loadingText: {
    fontSize: 15,
    color: Theme.colors.textMuted,
    textAlign: 'center',
    paddingVertical: Theme.spacing.lg,
  },
  closeButton: {
    alignSelf: 'flex-end',
    marginTop: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.borderRadius.sm,
  },
  closeButtonText: {
    color: Theme.colors.white,
    fontWeight: '700',
  },
});
